name: Java CI with Gradle

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run unit test
        run: |
          mkdir -p ../relativitization-art/assets
          mkdir -p ../relativitization-art/assets/fonts
          mkdir -p ../relativitization-art/assets/images
          mkdir -p ../relativitization-art/assets/music
          mkdir -p ../relativitization-art/assets/skin
          mkdir -p ../relativitization-art/assets/sounds
          mkdir -p ../relativitization-art/assets/translations
          mkdir -p ../relativitization-art/resources
          ./gradlew clean test